# Data Contract para el conjunto de datos de noticias extraídas.
# Define la estructura esperada, los tipos de datos y las reglas de calidad.

contract_name: "schema_noticias_extraidas"
schema_version: "1.1"
purpose: "Especificar la estructura y las restricciones de calidad para los registros de noticias obtenidos mediante web scraping."

dataset:
  # Define las columnas y sus propiedades.
  columns:
    - name: id
      type: string
      description: "Identificador único de 16 caracteres (hash SHA1 de la URL)."
      constraints:
        required: true
        unique: true
        pattern: "^[a-f0-9]{16}$" # Actualizado para coincidir con el nuevo scraper

    - name: titulo
      type: string
      description: "El encabezado o título principal del artículo."
      constraints:
        required: true
        min_length: 5
        max_length: 500

    - name: fecha
      type: date
      description: "Fecha de publicación del artículo en formato AAAA-MM-DD. Puede ser nulo si no está disponible."
      nullable: true # Equivalente a required: false
      format: "YYYY-MM-DD"

    - name: url
      type: string
      description: "El enlace completo y directo al artículo original."
      constraints:
        required: true
        pattern: "^https?://[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}" # Patrón de URL más genérico

    - name: fuente
      type: string
      description: "Nombre del sitio web de donde se extrajo la noticia."
      constraints:
        required: true
        one_of: ["Reuters", "BBC Mundo", "El Universal"] # Permite futuras fuentes

    - name: autor
      type: string
      description: "El nombre del autor o la agencia que redactó la noticia. Puede ser nulo."
      nullable: true

    - name: capturado_ts
      type: datetime
      description: "Marca de tiempo en formato ISO 8601 (UTC) que indica cuándo se realizó la captura."
      constraints:
        required: true
      format: "ISO8601"

    - name: categoria
      type: string
      description: "Categoría o sección a la que pertenece la noticia (ej. 'Mundo', 'Deportes')."
      nullable: true

# Reglas de validación a nivel de conjunto de datos.
quality_assertions:
  - check: "unicidad_de_urls"
    description: "Cada URL en el conjunto de datos debe ser única para evitar registros duplicados."
    expression: "COUNT(DISTINCT url) = COUNT(url)"

  - check: "formato_valido_de_fecha"
    description: "El campo 'fecha' debe cumplir con el formato AAAA-MM-DD o ser nulo."
    expression: "fecha IS NULL OR REGEXP_MATCHES(fecha, '^\\d{4}-\\d{2}-\\d{2}$')"

  - check: "no_fechas_futuras"
    description: "La fecha de publicación no puede ser posterior a la fecha actual."
    expression: "fecha IS NULL OR fecha <= CURRENT_DATE"